$(document).ready(function(){var $headerStar=$('.favheader .star');var tocStarSelector='.row .star,.postingtitle .star,#mapcontainer .star';var $tocStars;var listBits;var listToken;var favlist;var isMobileMode=$('body').hasClass('mobile');CL.when.localStorageAvailable.done(function(ls){var mine=ls.getItem('cl_fav');listBits=parseString(mine);listToken=listBits.token||newToken();favlist=listBits.list;if(window.expFaves){expFaves.split(',').forEach(function(id){delete favlist[id];});syncState();}
var page=unescape(CL.url.param('fl'));if(favListString()!==page){var urlToken=parseString(page).token;if(listToken!==urlToken){$('.sharedFavList').show();}else{$('.oldFavList').show();}}});function parseString(raw){var list={};var token;if(raw&&raw.length>5){raw=Base64.decode(raw);raw=raw.split(':');token=raw.shift();if(raw.length&&raw[0].length){var bits=raw[0].split(',');var base=parseInt(bits.shift(),10);if(!isNaN(base)){list[base]=1;bits.forEach(function(id){var numericID=parseInt(id,10);if(!isNaN(numericID)){list[base+numericID]=1;}});}}}
return{token:token,list:list};}
function newToken(){return Math.random().toString(36).substring(5);}
function favListString(){var base=0;var bits=[];var list=Object.keys(favlist).sort();list.forEach(function(id){if(isNaN(id)){return;};bits.push(id-base);base=base||id;});return Base64.encode(listToken+':'+bits.join(','));}
function toggleFav($t){var pid=pID||$t.data('pid');if($t.hasClass('fav')){delete favlist[pid];}else{if(Object.keys(favlist).length>=200){alert('Sorry, there is currently a limit of 200 favorites at a time');return;}
favlist[pid]=1;}
$t.toggleClass('fav');syncState();}
function initStars(){var useStarHint=typeof starHint!=='undefined';$tocStars=$(tocStarSelector);CL.when.localStorageAvailable.fail(function(){$tocStars.hide();});CL.when.localStorageAvailable.done(function(){$tocStars.addClass('v');if(useStarHint){$tocStars.attr('title',starHint);}
$tocStars.each(function(){var $this=$(this);var pid=pID||$this.parents('p.row').data('pid');$this.toggleClass('fav',favlist[pid]==1).data('pid',pid);});$headerStar.off('click.star').on('click.star',function(){if($headerStar.hasClass('fav')){$tocStars.filter('.fav').click();}else{$tocStars.not('.fav').click();}});$tocStars.off('click.star').on('click.star',function(e){e.stopPropagation();toggleFav($(this));});syncState();});}
function updateFavCount(){var fav_list_length=Object.keys(favlist).length;var $favorites=$('#favorites');var $favlink=$('.favlink');var $favlinkcontainer=$('.favlinkcontainer');$favorites.find('.n').text(fav_list_length);$favorites.toggle(!!(window.location.href.match(/\/favorites/)||fav_list_length!==0||isMobileMode));if(fav_list_length>0){$favlink.removeClass('off').attr('href','/favorites?fl='+favListString());$favlinkcontainer.show();}else{$favlink.addClass('off').attr('href','#');if(!isMobileMode){$favlinkcontainer.hide();}}}
function updateHeaderStar(){var countAllFavs=$('.row .star.fav').length;if(!$tocStars){$tocStars=$(tocStarSelector);}
if($tocStars.length===countAllFavs){$headerStar.removeClass('half').addClass('fav');}else if(countAllFavs===0){$headerStar.removeClass('fav half');}else{$headerStar.removeClass('fav').addClass('half');}}
function syncState(){CL.when.localStorageAvailable.done(function(ls){ls.setItem('cl_fav',favListString());updateFavCount();updateHeaderStar();});}
initStars();CL.extend('favorites',{init:initStars,sync:syncState});});