$(document).ready(function(){var $body=$('body');if(!$body.hasClass('toc')){return;}
var isMobileMode=$body.hasClass('mobile');var $searchform=$('#searchform');var $query=$('#query');var makeCatAbbUI=function(){var catAbb=$('#catAbb'),catAbbUI=catAbb.clone()
.attr({id:'catAbbUI',name:''}),acat=catAbb.find('option:selected')
.data('acat');if(acat){catAbbUI.val(acat);}
catAbbUI.find('option[data-acat]').remove();catAbb.hide().after(catAbbUI);}
makeCatAbbUI();$('#catAbbUI').on('change',function(e){$('#useMap').prop('checked',false);flipCatAndSubmit($('#catAbbUI').find('option:selected').val());});$('#catAbb, input.min, input.max').prop('disabled',false);var addFloater=function(){var $floater=$('#floater');var $payload=$floater.find('img.payload');var visible=false;if(!isMobileMode){$('.i').on('mouseover',function(){var imgID=$(this).data('id');if(imgID){$floater.show();$payload.attr('src',imgURL(imgID,'300x300'))
.on('load',function(){$('#floater').addClass('f');});visible=true;}})
.on('mouseout',function(){$floater.hide().removeClass('f');$payload.attr('src','');visible=false;})
.on('mousemove',function(e){if(visible){$('#floater').css({'left':e.pageX+15+'px','top':e.pageY+15+'px'});}});}}
var removeFloater=function(){$('.i').off();$('#floater').hide();}
var markEmtpyThumbnails=function(){$('p.row .i')
.not('[data-id]')
.not('.empty')
.addClass('empty')
.attr('title','no image');};var countHoods=function(){$('span#hoodcount').text($('#nh :checked').length||$('#nh :selected').length||'all');};var toggleHoods=function(){$('#hoodtogon, #hoodtogoff').toggle();$('#nh').slideToggle(100);$('select#nh').toChecklist({addScrollBar:false,showSelectedItems:true,submitDataAsArray:false});$('#nh').on('click',countHoods);countHoods();};var viewModes={};var tocmodeCookie=function(val,time){var cookieName='cl_tocmode';var mode;if(typeof val==='undefined'){mode=CL.cookies.getItem(cookieName);if(mode){mode.split(',').forEach(function(tuple){tuple=tuple.split(':');if(tuple.length===1){viewModes[catType]=tuple[0];}else{viewModes[tuple[0]]=tuple[1];}});mode=viewModes[catType];}
mode=mode==='show'?'pic':mode;return mode||(((catType==='hhh'&&((catAbb!='hsw')&&(catAbb!='hou')&&(catAbb!='sha')&&(catAbb!='sbw')&&(catAbb!='rew')))&&(areaRegion==='TX'||areaRegion==='FL'))?(pagemode==='mobile'?'pic':'map'):(pagemode==='mobile'?'pic':'list'));}else{var date=new Date();time=time||date.getTime();date.setTime(time+(365*24*60*60*1000));viewModes[catType]=val;var allCatModes=Object.keys(viewModes).map(function(cat){return cat+':'+viewModes[cat];}).join(',');CL.cookies.removeItem(cookieName,{path:'/'});CL.cookies.setItem(cookieName,allCatModes,{expires:date,path:'/',domain:CL.url.baseDomain});}};var populateImageSpans=function(size){size=size||'50x50c';$('.i').each(function(){var img_id=$(this).data('id');if(img_id){$(this).find('img').remove().end().append('<img alt="" src="'+imgURL(img_id,size)+'">');}});};var imgURL=function(img_id,size){var cPos=img_id.indexOf(':');return imageHost+'/'+img_id.substr(cPos+1)+'_'+size+'.jpg';};var getSubarea=function(url){var match=url.match(/\/search\/...\/(...)/);if(match){return match[1];}
match=url.match(/\/(...)\/...\//);if(match){return match[1];}};var flipCatAndSubmit=function(cat){$searchform.find('#catAbb').val(cat).end().submit();};var isMapMode=$('#useMap').prop('checked');var $modeLinks=$('.toc_legend a.mode');var viewMode=function(mode){var validModes=['list','pic','grid','map'];if(validModes.indexOf(mode)===-1){return;}
if(mode==='map'&&!showMapTabs){mode='list';}
$modeLinks.removeClass('sel');if(mode==='map'){$('#mapview').addClass('sel');if(!$('#map').length){$('#zoomtoposting').val('');$('#useMap').prop('checked',true);$searchform.submit();}
tocmodeCookie(mode);}else{tocmodeCookie(mode);$('#'+mode+'view').addClass('sel');if(isMapMode){$('#useMap').prop('checked',false);$searchform.submit();return;}
$body.removeClass(validModes.join(' ')).addClass(mode);if(mode=='list'){$('p.row').show();}else if(mode=='pic'){$('p.row').show();addFloater();populateImageSpans('50x50c');markEmtpyThumbnails();}else if(mode=='grid'){removeFloater();populateImageSpans('300x300');markEmtpyThumbnails();}}};$modeLinks.on('click',function(e){e.preventDefault();var $this=$(this);if($this.hasClass('sel')){return;}
viewMode($this.data('view'));});var modeToShow=tocmodeCookie();if(isMapMode){modeToShow='map';}
var hashMode=(window.location.hash||'').replace('#','');if(hashMode){modeToShow=hashMode;window.location.hash='';}
viewMode(modeToShow);var $searchInputs=$searchform.find('#searchtable').find('input, select');var hasFormChanged=function(){var changed=false;$searchInputs.each(function(i,el){var $el=$(el);var val=$el.val();if(val!==CL.url.param($el.attr('name'))&&val!==$el.attr('placeholder')){changed=true;return false;}});return changed;};$('.savesearch').on('click',function(e){if(hasFormChanged()){e.preventDefault();$searchform.append('<input type="hidden" name="save" value="1">').submit();}});if($.fn.DefaultValue&&!('placeholder'in document.createElement('input'))){var $min=$('input.min');var $max=$('input.max');$min.DefaultValue($min.attr('placeholder'));$max.DefaultValue($max.attr('placeholder'));$query.DefaultValue($query.attr('placeholder'));}
$('#catAbb').on('change',function(){if(isMapMode){$searchform.attr('action','/search/'+$('#catAbb').val());}
$searchform.submit();});$searchform.on('change','input, select',function(){$('#searchbtn').addClass('clickme');});$('#nh').hide().removeAttr('disabled');newSel=$('#nh').clone();newSel.find('#all').remove();$('#nh').replaceWith(newSel);$('#hoodtogon, #hoodtitle').show();$('#hoodtitle').on('click',function(e){e.preventDefault;toggleHoods();});countHoods();$body.on('click',function(e){if(!$(e.target).parents('#hoodpicker').length){$('#hoodtogon').show();$('#hoodtogoff').hide();$('#nh').slideUp(100);}});$('#satabs a').on('click',function(e){e.preventDefault();var t=$searchform.attr('action').match(/\/search\/.../);var s=getSubarea($(this).attr('href'));if(s){t=t+"/"+s;}
$searchform.attr('action',t);$('select#nh').prop('disabled',true);$searchform.submit();});$("a.gc,#searchlegend a").click(function(e){e.preventDefault();flipCatAndSubmit($(this).data('cat'));});if($('div.container').html()){$('#toc_rows blockquote').first().hide();}
$('span.itemsfound').prependTo('div.container');$('a.maptag').click(function(){var mapTagPostingID=$(this).data('pid');$('#useMap').prop('checked',true);$('#zoomtoposting').val(mapTagPostingID);$searchform.submit();});$('.experimentalFeature a').on('click',function(e){var query=$(this).data('query');if(query){e.preventDefault();$query.val(query);$searchform.submit();}});(function(e){var $catfilterbox=$('.catfilterbox');var $catfilter=$catfilterbox.find('.catfilter');var $catfilterlink=$('.catfilterlink');var $dropdown=$catfilterbox.find('.dropdown');var $catrow=$catfilter.find('.catrow');var $num=$catfilterbox.find('.summary .num');var $filterbutton=$catfilterbox.find('.filterbutton');var $excats=$('#excats');var isOpen=false;var totalCats=$catrow.length;var exCats=CL.url.param('excats');exCats=exCats?exCats.split('-'):[];var prevVal=0;exCats=exCats.map(function(val){var retVal=parseInt(val,10)+prevVal;prevVal=retVal;return retVal;});var excludedCount=exCats.length;var state=Array.prototype.map.call($catrow,function(el){var $el=$(el);var ids=String($el.data('ids')).split(',').map(parseFloat);return{$el:$el,excluded:exCats.indexOf(ids[0])>-1,ids:ids}});var isDragging=false;var exclude=true;var startIndex=0;var hasBeenToggled=[];var toggle=function(index){var s=state[index];var $el=s.$el;if(exclude!==s.excluded){$el.toggleClass('ex in');s.excluded=!s.excluded;excludedCount=exclude?excludedCount+1:excludedCount-1;}
$el.addClass('ip');$query.trigger('change');};var toggleRange=function(toIndex){var dragDown=(toIndex>startIndex);$catrow.each(function(i,el){if(hasBeenToggled[i]){return;}
if(dragDown){if(i>startIndex&&i<=toIndex){hasBeenToggled[i]=true;toggle(i);}}else{if(i<startIndex&&i>=toIndex){hasBeenToggled[i]=true;toggle(i);}}});};var startDrag=function(el){isDragging=true;startIndex=$catrow.index(el);toggle(startIndex);};var endDrag=function(){isDragging=false;$catrow.removeClass('ip');hasBeenToggled=[];var idList=[];state.forEach(function(cat){if(cat.excluded){idList.push.apply(idList,cat.ids);}});var prevVal=0;idList=idList
.sort(function(a,b){return a-b;})
.map(function(val){var retVal=val-prevVal;prevVal=val;return retVal;});$excats.val(idList.join('-'));};$catrow.on('mousedown touchstart',function(e){if(e.which===3){return;}
e.preventDefault();exclude=$(this).hasClass('in');startDrag(this);});$catrow.on('mouseup',endDrag);$catrow.on('mouseenter',function(e){if(!isDragging){return;}
toggleRange($catrow.index(this));});$catfilter.on('mousedown',function(e){e.preventDefault();});$catfilter.on('mouseleave',function(e){if(!isDragging){return;}
var $this=$(this);var top=$this.offset().top;var bottom=top+$this.outerHeight();if(e.pageY<=top){toggleRange(0);}else if(e.pageY>=bottom){toggleRange($catrow.last().index());}
endDrag();});$catfilterlink.on('click',function(e){e.preventDefault();e.stopPropagation();isOpen=!isOpen;$dropdown.toggle(isOpen);});$(document).on('mousedown',function(e){if(!isOpen){return;}
if(!($dropdown.is(e.target)||$dropdown.find(e.target).length)&&!$catfilterlink.is(e.target)){e.stopPropagation();isOpen=!isOpen;$dropdown.toggle(isOpen);}});$filterbutton.on('click',function(){$searchform.submit();});}());});